### ISSUE TITLE
[BUG] - Agent Error: 2421 // Starcraft 2 

### ISSUE THREAD

**Issue by emmanu3lsilva** [barncastle/Battle.Net-Installer#1]
Hello,

I've got an issue trying to use this nice tool of yours. I've been trying many combination but doesn't seem to make it work on my side.

Here is the error : 

`C:\Users\X\Documents\PW>bnetinstaller.exe --prod s2 --lang enus --dir "C:\Program Files (x86)\StarCraft II\"
Authenticating
Queuing Install
Starting Install

Unhandled exception. System.AggregateException: One or more errors occurred. (Agent Error: 2421)
 ---> System.Exception: Agent Error: 2421
   at BNetInstaller.Endpoints.BaseEndpoint.Deserialize(HttpResponseMessage response)
   at BNetInstaller.Endpoints.Update.UpdateEndpoint.Post()
   at BNetInstaller.Program.InstallProduct(Options options, AgentApp app)
   at BNetInstaller.Program.Run(Options options)
   at BNetInstaller.Program.<>c.<<Main>b__0_1>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at BNetInstaller.Program.Main(String[] args)`

Thanks 

Emmanuel

**Comment by barncastle** [comment]
I've tested this myself and found a few changes to the SC2 product - which have been fixed in the latest release - but *probably* aren't related to your issue. These `Agent Error`s are official Blizzard error codes meaning it's more likely to be an issue with your battle.net app and/or access to this product rather than this tool.

Firstly I'd first try using the [new release](https://github.com/barncastle/Battle.Net-Installer/releases/tag/v1.3) and ensure your battle.net app is up to date. After that I'd see if you can install SC2 from battle.net directly, if you can then the issue is definitely with this tool and will need further investigation.

Also, there may be some information on what error 2421 means in one of the `AgentErrors-*.log` files in `C:\ProgramData\Battle.net\Agent\Agent.XXXX\Logs` (`XXXX` being the highest build number) which may help.

**Comment by emmanu3lsilva** [comment]
Hello barncastle,

The last release (v1.3) work nicely ! 

My problem is no more. 

Y=Thank you very much for your quick answer and release.

Emmanuel
