### ISSUE TITLE
Unable to install games, timeout issue

### ISSUE THREAD

**Issue by nick71223** [barncastle/Battle.Net-Installer#13]
whenever i attempt to install a game it comes back with this 

Unhandled exception. System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError , CancellationToken )
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 )
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean )
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage , Boolean , CancellationToken )
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage , Boolean , Boolean , CancellationToken )
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage , HttpCompletionOption , CancellationTokenSource , Boolean , CancellationTokenSource , CancellationToken )
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception , Boolean , HttpResponseMessage , CancellationTokenSource , CancellationToken , CancellationTokenSource )
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage , HttpCompletionOption , CancellationTokenSource , Boolean , CancellationTokenSource , CancellationToken )
   at BNetInstaller.Requester.SendAsync(String endpoint, HttpVerb verb, String content)
   at BNetInstaller.Requester.SendAsync[T](String endpoint, HttpVerb verb, T payload)
   at BNetInstaller.Endpoints.ProductEndpoint.Post()
   at BNetInstaller.Program.Run(Options options)
   at BNetInstaller.Program.Main(String[] args)
   at BNetInstaller.Program.<Main>(String[] args)

**Comment by barncastle** [comment]
Can you provide the TACT Product, Agent UID and locale you're using please?

**Comment by barncastle** [comment]
I've now tested and can confirm that that product and endpoint is working on my machine with the latest version of Battle.Net, which means this is likely an issue on your end with either your network and/or Battle.Net client.

The error is indicating that the Agent.exe is failing to speak to Blizzard's game API which I believe is separate from their authentication API. At the point it is definitely working you should see a list of stats including a "Progress" figure - this may stick for a few minutes before moving past 0%. 

The usual checklist of things to do:
- Ensure Battle.Net is up to date
- Kill all Agent.exe and Battle.net.exe processes
- Sign out and back in to Battle.Net
- Try installing another game through this application and see if you get to the "Progress" loop (Starcraft 2 is my go to)
- Try installing another game via Battle.Net itself
- Try reinstalling Battle.Net altogether

Can you try the above and let me know if any of these correct the issue? If not I'll investigate further.

**Comment by nick71223** [comment]
> I've now tested and can confirm that that product and endpoint is working on my machine with the latest version of Battle.Net, which means this is likely an issue on your end with either your network and/or Battle.Net client.
> 
> The error is indicating that the Agent.exe is failing to speak to Blizzard's game API which I believe is separate from their authentication API. At the point it is definitely working you should see a list of stats including a "Progress" figure - this may stick for a few minutes before moving past 0%.
> 
> The usual checklist of things to do:
> 
> * Ensure Battle.Net is up to date
> * Kill all Agent.exe and Battle.net.exe processes
> * Sign out and back in to Battle.Net
> * Try installing another game through this application and see if you get to the "Progress" loop (Starcraft 2 is my go to)
> * Try installing another game via Battle.Net itself
> * Try reinstalling Battle.Net altogether
> 
> Can you try the above and let me know if any of these correct the issue? If not I'll investigate further.

i have tried all of these things and nothing has changed, i have no idea what im doing wrong

**Comment by nick71223** [comment]
> Just to confirm installing other games through this application and through Battle.Net directly, both work fine? If so, there wouldn't be any reason you'd be blacklisted from this title, either due to account, location, VPN etc?
> 
> [Here](https://i.ibb.co/WtHfLBn/Capture.png) are the product details I'm testing with. Can you confirm that they're identical to yours (ignoring the directory) please?

installing via battle.net itself works fine

i cannot seem to install any games from your program at all

and yes those are identical

**Comment by barncastle** [comment]
I'm at a bit of a loss really. 

It could potentially be a port conflict. The app uses port 5050, I don't suppose anything else is using that?

Maybe try running as administrator. Doubt it'll help but it's not been tried yet.

**Comment by xaetacore** [comment]
I'm having the exact same issue

**Comment by barncastle** [comment]
Is this the same product?

I assume that you've gone through all of the above to rule out your Battle.Net app and anything else that may be conflicting on port 5050?

If so, could you check/share your latest `AgentErrors-*.log` file from `C:\ProgramData\Battle.net\Agent\Agent.XXXX\Logs` (XXXX being the highest build number) as it may contain some additional information.
