### ISSUE TITLE
BNetInstaller.exe --prod zeus --uid zeus --lang enUS --dir "D:\cod"

### ISSUE THREAD

**Issue by Auditormadness9** [barncastle/Battle.Net-Installer#21]
```
Authenticating
Queuing Install
Starting Install

Unhandled exception. System.Exception: Agent Error: 2421
 ---> System.Exception: {
  "error": 2421
}
   --- End of inner exception stack trace ---
   at BNetInstaller.Endpoints.BaseEndpoint.ValidateResponse(JToken response, String content)
   at BNetInstaller.Endpoints.BaseEndpoint.Deserialize(HttpResponseMessage response)
   at BNetInstaller.Endpoints.Update.UpdateEndpoint.Post()
   at BNetInstaller.Program.InstallProduct(Options options, AgentApp app)
   at BNetInstaller.Program.Run(Options options)
   at BNetInstaller.Program.Main(String[] args)
   at BNetInstaller.Program.<Main>(String[] args)
```

**Comment by barncastle** [comment]
Error 2421 is documented in the [ReadMe](https://github.com/barncastle/Battle.Net-Installer#error-messages-and-codes). It means your PC doesn't meet the minimum specs - most likely not enough disk space.
