### ISSUE TITLE
i get this error

### ISSUE THREAD

**Issue by sdvn** [barncastle/Battle.Net-Installer#8]
D:\d2r>BNetInstaller.exe --prod osib --uid osi_beta --lang enus --dir "D:\D2R"
Unhandled exception. System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName, String arguments)
   at BNetInstaller.AgentApp.StartProcess()
   at BNetInstaller.AgentApp..ctor()
   at BNetInstaller.Program.Run(Options options)
   at BNetInstaller.Program.Main(String[] args)
   at BNetInstaller.Program.<Main>(String[] args)

**Comment by barncastle** [comment]
The tool is failing to start Battle.net for some reason. Do you have
Battle.net installed (link is in the README)? If you do could you try
running as admin?

Also out of curiosity, what version of the tool are you using? Is it 1.3 or
1.4?

**Comment by sdvn** [comment]
thank for reply, i forgot open batle.net
